### PR TITLE
Adapt for SMASH-vHLLE-hybrid hypersurface sampling

### PR DESCRIPTION
**Pull request by NGoetz**
This PR

- Adds the option to read from a vHLLE hypersurface
- Includes the EventWriter for SMASH

### CODE REVIEW

**Comment by vlvovch** [comment]
@NGoetz Thanks! I've made a couple of adjustments, please check they are good:
- Added default parameter values for bulk_correction and speed_of_sound_squared
- Added the setting of bulk corrections and speed of sound squared when initializing the event generator
- Added reading the bulk pressure from MUSIC

**Comment by NGoetz** [comment]
Yes they are good! I just have one issue - when using this branch with the related ThermalFIST branch, I get a compiler error:
```In file included from /home/niklas/Desktop/fist-sampler/FistSampler.cpp:20:
/home/niklas/Desktop/fist-sampler/include/FistSamplerHelperFunctions.h: In function ‘thermalfist::HypersurfaceEventGenerator* FistSampler::CreateEventGeneratorFromHypersurface(FistSampler::FistSamplerParameters&, const ParticlizationHypersurface&)’:
/home/niklas/Desktop/fist-sampler/include/FistSamplerHelperFunctions.h:223:35: error: call of overloaded ‘HypersurfaceEventGenerator(thermalfist::ThermalParticleSystem*&, thermalfist::EventGeneratorConfiguration&, const ParticlizationHypersurface*)’ is ambiguous
  223 |       TPS, configMC, &hypersurface);
      |                                   ^
In file included from /home/niklas/Desktop/fist-sampler/Thermal-FIST/include/HRGEventGenerator.h:20,
                 from /home/niklas/Desktop/fist-sampler/FistSampler.cpp:14:
/home/niklas/Desktop/fist-sampler/Thermal-FIST/include/HRGEventGenerator/HypersurfaceSampler.h:272:5: note: candidate: ‘thermalfist::HypersurfaceEventGenerator::HypersurfaceEventGenerator(thermalfist::ThermalParticleSystem*, const thermalfist::EventGeneratorConfiguration&, const ParticlizationHypersurface*, double, bool, bool, double)’
  272 |     HypersurfaceEventGenerator(
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~
/home/niklas/Desktop/fist-sampler/Thermal-FIST/include/HRGEventGenerator/HypersurfaceSampler.h:254:5: note: candidate: ‘thermalfist::HypersurfaceEventGenerator::HypersurfaceEventGenerator(thermalfist::ThermalParticleSystem*, const thermalfist::EventGeneratorConfiguration&, const ParticlizationHypersurface*, const thermalfist::RandomGenerators::HypersurfaceMomentumGenerator::HypersurfaceMomentumGeneratorConfiguration&)’
  254 |     HypersurfaceEventGenerator(
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by NGoetz** [comment]
I a side effect of my changes which I overlooked before. When running the samper with the SMASH decay and particle list files, I now get the warning 

```
**WARNING** K*(892)0 (313): Particle marked unstable but no decay channels found!
**WARNING** anti-K*(892)0 (-313): Particle marked unstable but no decay channels found!
**WARNING** K*(892)+ (323): Particle marked unstable but no decay channels found!
**WARNING** K*(892)- (-323): Particle marked unstable but no decay channels found!
**WARNING** a0(980)0 (9000111): Particle marked unstable but no decay channels found!
**WARNING** Delta++ (2224): Particle marked unstable but no decay channels found!
**WARNING** anti-Delta+ (-2214): Particle marked unstable but no decay channels found!
**WARNING** Delta+ (2214): Particle marked unstable but no decay channels found!
**WARNING** anti-Delta0 (-2114): Particle marked unstable but no decay channels found!
**WARNING** Delta0 (2114): Particle marked unstable but no decay channels found!
**WARNING** Further warnings are discarded...
```
This could be because of the edits to the particle list I performed, but for example for 313 there are still decay channels. Do you have an idea what could be the reason?

**Comment by vlvovch** [comment]
> Yes they are good! I just have one issue - when using this branch with the related ThermalFIST branch, I get a compiler error:
> 
> ```
> /home/niklas/Desktop/fist-sampler/include/FistSamplerHelperFunctions.h: In function ‘thermalfist::HypersurfaceEventGenerator* FistSampler::CreateEventGeneratorFromHypersurface(FistSampler::FistSamplerParameters&, const ParticlizationHypersurface&)’:
> /home/niklas/Desktop/fist-sampler/include/FistSamplerHelperFunctions.h:223:35: error: call of overloaded ‘HypersurfaceEventGenerator(thermalfist::ThermalParticleSystem*&, thermalfist::EventGeneratorConfiguration&, const ParticlizationHypersurface*)’ is ambiguous
>   223 |       TPS, configMC, &hypersurface);
>       |                                   ^
> In file included from /home/niklas/Desktop/fist-sampler/Thermal-FIST/include/HRGEventGenerator.h:20,
>                  from /home/niklas/Desktop/fist-sampler/FistSampler.cpp:14:
> /home/niklas/Desktop/fist-sampler/Thermal-FIST/include/HRGEventGenerator/HypersurfaceSampler.h:272:5: note: candidate: ‘thermalfist::HypersurfaceEventGenerator::HypersurfaceEventGenerator(thermalfist::ThermalParticleSystem*, const thermalfist::EventGeneratorConfiguration&, const ParticlizationHypersurface*, double, bool, bool, double)’
>   272 |     HypersurfaceEventGenerator(
>       |     ^~~~~~~~~~~~~~~~~~~~~~~~~~
> /home/niklas/Desktop/fist-sampler/Thermal-FIST/include/HRGEventGenerator/HypersurfaceSampler.h:254:5: note: candidate: ‘thermalfist::HypersurfaceEventGenerator::HypersurfaceEventGenerator(thermalfist::ThermalParticleSystem*, const thermalfist::EventGeneratorConfiguration&, const ParticlizationHypersurface*, const thermalfist::RandomGenerators::HypersurfaceMomentumGenerator::HypersurfaceMomentumGeneratorConfiguration&)’
>   254 |     HypersurfaceEventGenerator(
>       |     ^~~~~~~~~~~~~~~~~~~~~~~~~~
> ```

I have pushed a new commit to Thermal-FIST which fixes this issue, please check.

**Comment by vlvovch** [comment]
> ```
> 
> ```
> 
> 
>     
>   
> 
> This could be because of the edits to the particle list I performed, but for example for 313 there are still decay channels. Do you have an idea what could be the reason?

@NGoetz 

I've looked into this. Yes, the issue stems from the removal of decays containing \sigma. Now, some particles have fewer decay channels listed than the # of decay channels specified, e.g. for $\eta'$:
```text
...
331                                  # eta'
4                                    # 4 decay channels
0.291507        22 113               # eta' -> gamma + rho0
0.0264273       22 223               # eta' -> gamma + omega
0.0223926       22 22                # eta' -> gamma + gamma

9000111                              # a0(980)0
...
```

This leads to a corrupted reading of the input file.

To remedy this issue, my suggestion is the following: Add $\sigma$ resonance and its decay channels back to the list, but set the degeneracy of $\sigma$ to zero in list.dat and list-charm.dat:
```text
9000221 sigma 0 0.8 0 -1 0 0 0 0 0 0 0.4 0.276
```

This way, $\sigma$ will never be sampled at particlization, but also all the decay channels will be correctly specified.

**Comment by NGoetz** [comment]
Thank you, I have adapted the lists accordingly and now all is working as expected. The ambiguity issue has been fixed, too.

**Comment by vlvovch** [comment]
Update the reference to Thermal-FIST submodule. Looks good now, merging.

**Pull request merged**
